// Code generated by go-swagger; DO NOT EDIT.

package restmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Framework framework
// swagger:model Framework

type Framework struct {

	// the name of the deep learning framework (e.g. caffe, torch, tensorflow)
	Name string `json:"name,omitempty"`

	// the version of the specific framework to use.
	Version string `json:"version,omitempty"`
}

/* polymorph Framework name false */

/* polymorph Framework version false */

// Validate validates this framework
func (m *Framework) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Framework) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Framework) UnmarshalBinary(b []byte) error {
	var res Framework
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
