// Code generated by go-swagger; DO NOT EDIT.

package restmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TrainingUpdate training update
// swagger:model TrainingUpdate

type TrainingUpdate struct {

	// The status action to be executed on the training job. (Currently only `halt` is supported.)
	Status string `json:"status,omitempty"`
}

/* polymorph TrainingUpdate status false */

// Validate validates this training update
func (m *TrainingUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TrainingUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TrainingUpdate) UnmarshalBinary(b []byte) error {
	var res TrainingUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
