// Code generated by go-swagger; DO NOT EDIT.

package training_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetEMetricsHandlerFunc turns a function with the right signature into a get e metrics handler
type GetEMetricsHandlerFunc func(GetEMetricsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEMetricsHandlerFunc) Handle(params GetEMetricsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetEMetricsHandler interface for that can handle valid get e metrics params
type GetEMetricsHandler interface {
	Handle(GetEMetricsParams, interface{}) middleware.Responder
}

// NewGetEMetrics creates a new http.Handler for the get e metrics operation
func NewGetEMetrics(ctx *middleware.Context, handler GetEMetricsHandler) *GetEMetrics {
	return &GetEMetrics{Context: ctx, Handler: handler}
}

/*GetEMetrics swagger:route GET /v1/logs/{model_id}/emetrics TrainingData getEMetrics

Get evaluation metrics records, based on query

*/
type GetEMetrics struct {
	Context *middleware.Context
	Handler GetEMetricsHandler
}

func (o *GetEMetrics) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEMetricsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
