{{ if .Values.prometheus.deploy }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
        service: dlaas-alertmanager
    spec:
      containers:
      - name: alertmanager
{{ if eq .Values.arch "ppc64le" }}
        image: ibmcom/alertmanager-ppc64le:v0.8.0
{{ else }}
        image: quay.io/prometheus/alertmanager:v0.8.0
{{ end }}
        args:
          - -config.file=/etc/prometheus/alertmanager.yml
        ports:
        - name: alertmanager
          containerPort: {{.Values.prometheus.alertmanager_port}}
        volumeMounts:
        - name: config-volume-alertmanager
          mountPath: /etc/prometheus
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 32Mi

      volumes:
      - name: config-volume-alertmanager
        configMap:
          name: prometheus-alertmanager
{{ end }}
