apiVersion: v1
kind: Secret
metadata:
  name: trainer-secrets
  namespace: {{.Values.namespace}}
type: Opaque
data:
{{ if ne .Values.env "dev" }}
  DLAAS_MONGO_ADDRESS: {{.Values.mongo.address|b64enc}}
  DLAAS_MONGO_USERNAME: {{.Values.mongo.username|b64enc}}
  DLAAS_MONGO_PASSWORD: {{.Values.mongo.password|b64enc}}
  DLAAS_MONGO_CERT: {{.Values.mongo.cert}} #cert has already been base64 encoded
{{ end }}
  DLAAS_OBJECTSTORE_TYPE: {{.Values.objectstore.type|b64enc}}
  # auth_url needs to be the FQDN due to a limitation in the local S3 mock
  DLAAS_OBJECTSTORE_AUTH_URL: {{printf "http://s3.%s.svc.cluster.local" .Values.namespace |b64enc}}
  DLAAS_OBJECTSTORE_USER_NAME: {{.Values.objectstore.username|b64enc}}
  DLAAS_OBJECTSTORE_PASSWORD: {{.Values.objectstore.password|b64enc}}
