apiVersion: v1
kind: Secret
metadata:
  name: trainingdata-secrets
  namespace: {{.Values.namespace}}
type: Opaque
data:
  DLAAS_ELASTICSEARCH_ADDRESS: {{.Values.elasticsearch.address|b64enc}}
  DLAAS_ELASTICSEARCH_USERNAME: {{.Values.elasticsearch.username|b64enc}}
  DLAAS_ELASTICSEARCH_PASSWORD: {{.Values.elasticsearch.password|b64enc}}
  DLAAS_ELASTICSEARCH_CERT: {{.Values.elasticsearch.ssl_cert}} #cert has already been base64 encoded
