apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.docker.image_prefix}}lcm
  namespace: {{.Values.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.docker.image_prefix}}lcm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{.Values.docker.image_prefix}}lcm
    namespace: {{.Values.namespace}}
