apiVersion: v1
kind: Secret
metadata:
  name: lcm-secrets
  namespace: {{.Values.namespace}}
type: Opaque
data:
  DLAAS_ETCD_ADDRESS: {{.Values.etcd.address|b64enc}}
  DLAAS_ETCD_USERNAME: {{.Values.etcd.username|b64enc}}
  DLAAS_ETCD_PASSWORD: {{.Values.etcd.password|b64enc}}
  DLAAS_ETCD_PREFIX: {{.Values.etcd.prefix|b64enc}}
  DLAAS_ETCD_CERT: {{.Values.etcd.cert}} #assumed to be already encoded
  DLAAS_LEARNER_TAG: {{.Values.learner.tag|b64enc}}
