apiVersion: v1
kind: Service
metadata:
  name: ffdl-lcm
  labels:
    service: ffdl-lcm
    environment: {{.Values.env}}
  namespace: {{.Values.namespace}}
spec:
  ports:
  - name: grpc
    port: 80
    targetPort: 8443
  selector:
    service: ffdl-lcm
