apiVersion: v1
kind: Service
metadata:
  name: ffdl-trainer
  namespace: {{.Values.namespace}}
  labels:
    service: ffdl-trainer
    environment: {{.Values.env}}
spec:
{{ if .Values.services.expose_node_port }}
  type: NodePort
{{ end }}
  ports:
  - name: grpc
    port: 80
    targetPort: 8443
    nodePort: {{.Values.trainer.port}}
  selector:
    service: ffdl-trainer
