apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: {{.Values.namespace}}
spec:
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        service: mongo
        environment: local
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
{{ if eq .Values.arch "ppc64le" }}
          image: ibmcom/mongodb-ppc64le:3.6.0
{{ else }}
          image: mongo:3.0
{{ end }}

{{ if .Values.docker.pullPolicy }}
          imagePullPolicy: {{.Values.docker.pullPolicy}}
{{ end }}
          command:
            - mongod
            - "--smallfiles"
{{ if eq .Values.arch "ppc64le" }}
            - "--bind_ip_all"
{{ end }}
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: 200m
              memory: 128Mi

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{.Values.namespace}}
  labels:
    environment: local
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    service: mongo
