// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.ibm.com/ffdl/ffdl-core/restapi/api_v1/restmodels"
)

// GetEventEndpointOKCode is the HTTP code returned for type GetEventEndpointOK
const GetEventEndpointOKCode int = 200

/*GetEventEndpointOK Event description

swagger:response getEventEndpointOK
*/
type GetEventEndpointOK struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Endpoint `json:"body,omitempty"`
}

// NewGetEventEndpointOK creates GetEventEndpointOK with default headers values
func NewGetEventEndpointOK() *GetEventEndpointOK {
	return &GetEventEndpointOK{}
}

// WithPayload adds the payload to the get event endpoint o k response
func (o *GetEventEndpointOK) WithPayload(payload *restmodels.Endpoint) *GetEventEndpointOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get event endpoint o k response
func (o *GetEventEndpointOK) SetPayload(payload *restmodels.Endpoint) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventEndpointOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEventEndpointUnauthorizedCode is the HTTP code returned for type GetEventEndpointUnauthorized
const GetEventEndpointUnauthorizedCode int = 401

/*GetEventEndpointUnauthorized Unauthorized

swagger:response getEventEndpointUnauthorized
*/
type GetEventEndpointUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Error `json:"body,omitempty"`
}

// NewGetEventEndpointUnauthorized creates GetEventEndpointUnauthorized with default headers values
func NewGetEventEndpointUnauthorized() *GetEventEndpointUnauthorized {
	return &GetEventEndpointUnauthorized{}
}

// WithPayload adds the payload to the get event endpoint unauthorized response
func (o *GetEventEndpointUnauthorized) WithPayload(payload *restmodels.Error) *GetEventEndpointUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get event endpoint unauthorized response
func (o *GetEventEndpointUnauthorized) SetPayload(payload *restmodels.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventEndpointUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEventEndpointNotFoundCode is the HTTP code returned for type GetEventEndpointNotFound
const GetEventEndpointNotFoundCode int = 404

/*GetEventEndpointNotFound The model or event type cannot be found.

swagger:response getEventEndpointNotFound
*/
type GetEventEndpointNotFound struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Error `json:"body,omitempty"`
}

// NewGetEventEndpointNotFound creates GetEventEndpointNotFound with default headers values
func NewGetEventEndpointNotFound() *GetEventEndpointNotFound {
	return &GetEventEndpointNotFound{}
}

// WithPayload adds the payload to the get event endpoint not found response
func (o *GetEventEndpointNotFound) WithPayload(payload *restmodels.Error) *GetEventEndpointNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get event endpoint not found response
func (o *GetEventEndpointNotFound) SetPayload(payload *restmodels.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventEndpointNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEventEndpointGoneCode is the HTTP code returned for type GetEventEndpointGone
const GetEventEndpointGoneCode int = 410

/*GetEventEndpointGone If the trained model storage time has expired and it has been deleted. It only gets deleted if it not stored on an external data store.

swagger:response getEventEndpointGone
*/
type GetEventEndpointGone struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Error `json:"body,omitempty"`
}

// NewGetEventEndpointGone creates GetEventEndpointGone with default headers values
func NewGetEventEndpointGone() *GetEventEndpointGone {
	return &GetEventEndpointGone{}
}

// WithPayload adds the payload to the get event endpoint gone response
func (o *GetEventEndpointGone) WithPayload(payload *restmodels.Error) *GetEventEndpointGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get event endpoint gone response
func (o *GetEventEndpointGone) SetPayload(payload *restmodels.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventEndpointGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
