// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DownloadTrainedModelHandlerFunc turns a function with the right signature into a download trained model handler
type DownloadTrainedModelHandlerFunc func(DownloadTrainedModelParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DownloadTrainedModelHandlerFunc) Handle(params DownloadTrainedModelParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DownloadTrainedModelHandler interface for that can handle valid download trained model params
type DownloadTrainedModelHandler interface {
	Handle(DownloadTrainedModelParams, interface{}) middleware.Responder
}

// NewDownloadTrainedModel creates a new http.Handler for the download trained model operation
func NewDownloadTrainedModel(ctx *middleware.Context, handler DownloadTrainedModelHandler) *DownloadTrainedModel {
	return &DownloadTrainedModel{Context: ctx, Handler: handler}
}

/*DownloadTrainedModel swagger:route GET /v1/models/{model_id}/trained_model Models downloadTrainedModel

Downloads the trained model.

Downloads the trained model as ZIP archive.

*/
type DownloadTrainedModel struct {
	Context *middleware.Context
	Handler DownloadTrainedModelHandler
}

func (o *DownloadTrainedModel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDownloadTrainedModelParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
