// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	"github.ibm.com/ffdl/ffdl-core/restapi/api_v1/restmodels"
)

// GetLogsOKCode is the HTTP code returned for type GetLogsOK
const GetLogsOKCode int = 200

/*GetLogsOK Dump of the training log to-date

swagger:response getLogsOK
*/
type GetLogsOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetLogsOK creates GetLogsOK with default headers values
func NewGetLogsOK() *GetLogsOK {
	return &GetLogsOK{}
}

// WithPayload adds the payload to the get logs o k response
func (o *GetLogsOK) WithPayload(payload io.ReadCloser) *GetLogsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get logs o k response
func (o *GetLogsOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLogsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetLogsUnauthorizedCode is the HTTP code returned for type GetLogsUnauthorized
const GetLogsUnauthorizedCode int = 401

/*GetLogsUnauthorized Unauthorized

swagger:response getLogsUnauthorized
*/
type GetLogsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Error `json:"body,omitempty"`
}

// NewGetLogsUnauthorized creates GetLogsUnauthorized with default headers values
func NewGetLogsUnauthorized() *GetLogsUnauthorized {
	return &GetLogsUnauthorized{}
}

// WithPayload adds the payload to the get logs unauthorized response
func (o *GetLogsUnauthorized) WithPayload(payload *restmodels.Error) *GetLogsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get logs unauthorized response
func (o *GetLogsUnauthorized) SetPayload(payload *restmodels.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLogsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetLogsNotFoundCode is the HTTP code returned for type GetLogsNotFound
const GetLogsNotFoundCode int = 404

/*GetLogsNotFound The model cannot be found.

swagger:response getLogsNotFound
*/
type GetLogsNotFound struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Error `json:"body,omitempty"`
}

// NewGetLogsNotFound creates GetLogsNotFound with default headers values
func NewGetLogsNotFound() *GetLogsNotFound {
	return &GetLogsNotFound{}
}

// WithPayload adds the payload to the get logs not found response
func (o *GetLogsNotFound) WithPayload(payload *restmodels.Error) *GetLogsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get logs not found response
func (o *GetLogsNotFound) SetPayload(payload *restmodels.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLogsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
