// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	"github.ibm.com/ffdl/ffdl-core/restapi/api_v1/restmodels"
)

// GetMetricsOKCode is the HTTP code returned for type GetMetricsOK
const GetMetricsOKCode int = 200

/*GetMetricsOK Dump of the training log to-date

swagger:response getMetricsOK
*/
type GetMetricsOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetMetricsOK creates GetMetricsOK with default headers values
func NewGetMetricsOK() *GetMetricsOK {
	return &GetMetricsOK{}
}

// WithPayload adds the payload to the get metrics o k response
func (o *GetMetricsOK) WithPayload(payload io.ReadCloser) *GetMetricsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get metrics o k response
func (o *GetMetricsOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMetricsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetMetricsUnauthorizedCode is the HTTP code returned for type GetMetricsUnauthorized
const GetMetricsUnauthorizedCode int = 401

/*GetMetricsUnauthorized Unauthorized

swagger:response getMetricsUnauthorized
*/
type GetMetricsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Error `json:"body,omitempty"`
}

// NewGetMetricsUnauthorized creates GetMetricsUnauthorized with default headers values
func NewGetMetricsUnauthorized() *GetMetricsUnauthorized {
	return &GetMetricsUnauthorized{}
}

// WithPayload adds the payload to the get metrics unauthorized response
func (o *GetMetricsUnauthorized) WithPayload(payload *restmodels.Error) *GetMetricsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get metrics unauthorized response
func (o *GetMetricsUnauthorized) SetPayload(payload *restmodels.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMetricsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMetricsNotFoundCode is the HTTP code returned for type GetMetricsNotFound
const GetMetricsNotFoundCode int = 404

/*GetMetricsNotFound The training job cannot be found.

swagger:response getMetricsNotFound
*/
type GetMetricsNotFound struct {

	/*
	  In: Body
	*/
	Payload *restmodels.Error `json:"body,omitempty"`
}

// NewGetMetricsNotFound creates GetMetricsNotFound with default headers values
func NewGetMetricsNotFound() *GetMetricsNotFound {
	return &GetMetricsNotFound{}
}

// WithPayload adds the payload to the get metrics not found response
func (o *GetMetricsNotFound) WithPayload(payload *restmodels.Error) *GetMetricsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get metrics not found response
func (o *GetMetricsNotFound) SetPayload(payload *restmodels.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMetricsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
