// Code generated by go-swagger; DO NOT EDIT.

/*
Package server IBM Deep Learning as a Service (DLaaS)
DLaaS enables deep learning (DL) highly scalable training of models for multiple frameworks on GPUs. The [DLaaS user
guide](https://dlaas-guide.stage1.mybluemix.net/) provides more details on how to use the service, including examples.



    Schemes:
      https
    Host: gateway.watsonplatform.net
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json
    - application/octet-stream

swagger:meta
*/
package server
