apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: {{.Values.namespace}}
spec:
  ports:
  - port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: etcd
    etcd_node: etcd0
  name: etcd0
  namespace: {{.Values.namespace}}
spec:
  serviceName: etcd
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
        etcd_node: etcd0
      name: etcd0
    spec:
      containers:
      - command:
        - /usr/local/bin/etcd
        - --name
        - etcd0
        - --initial-advertise-peer-urls
        - http://etcd0:2380
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://etcd0:2379
        - --initial-cluster
        - etcd0=http://etcd0:2380
        - --initial-cluster-state
        - new
        image: quay.io/coreos/etcd:latest
        imagePullPolicy: IfNotPresent
        name: etcd0
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd0
  name: etcd0
  namespace: {{.Values.namespace}}
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd0
