// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEventTypeEndpointsParams creates a new GetEventTypeEndpointsParams object
// with the default values initialized.
func NewGetEventTypeEndpointsParams() *GetEventTypeEndpointsParams {
	var ()
	return &GetEventTypeEndpointsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEventTypeEndpointsParamsWithTimeout creates a new GetEventTypeEndpointsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEventTypeEndpointsParamsWithTimeout(timeout time.Duration) *GetEventTypeEndpointsParams {
	var ()
	return &GetEventTypeEndpointsParams{

		timeout: timeout,
	}
}

// NewGetEventTypeEndpointsParamsWithContext creates a new GetEventTypeEndpointsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEventTypeEndpointsParamsWithContext(ctx context.Context) *GetEventTypeEndpointsParams {
	var ()
	return &GetEventTypeEndpointsParams{

		Context: ctx,
	}
}

// NewGetEventTypeEndpointsParamsWithHTTPClient creates a new GetEventTypeEndpointsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEventTypeEndpointsParamsWithHTTPClient(client *http.Client) *GetEventTypeEndpointsParams {
	var ()
	return &GetEventTypeEndpointsParams{
		HTTPClient: client,
	}
}

/*GetEventTypeEndpointsParams contains all the parameters to send to the API endpoint
for the get event type endpoints operation typically these are written to a http.Request
*/
type GetEventTypeEndpointsParams struct {

	/*EventType
	  The type of event.

	*/
	EventType string
	/*ModelID
	  The id of the model.

	*/
	ModelID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get event type endpoints params
func (o *GetEventTypeEndpointsParams) WithTimeout(timeout time.Duration) *GetEventTypeEndpointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get event type endpoints params
func (o *GetEventTypeEndpointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get event type endpoints params
func (o *GetEventTypeEndpointsParams) WithContext(ctx context.Context) *GetEventTypeEndpointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get event type endpoints params
func (o *GetEventTypeEndpointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get event type endpoints params
func (o *GetEventTypeEndpointsParams) WithHTTPClient(client *http.Client) *GetEventTypeEndpointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get event type endpoints params
func (o *GetEventTypeEndpointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventType adds the eventType to the get event type endpoints params
func (o *GetEventTypeEndpointsParams) WithEventType(eventType string) *GetEventTypeEndpointsParams {
	o.SetEventType(eventType)
	return o
}

// SetEventType adds the eventType to the get event type endpoints params
func (o *GetEventTypeEndpointsParams) SetEventType(eventType string) {
	o.EventType = eventType
}

// WithModelID adds the modelID to the get event type endpoints params
func (o *GetEventTypeEndpointsParams) WithModelID(modelID string) *GetEventTypeEndpointsParams {
	o.SetModelID(modelID)
	return o
}

// SetModelID adds the modelId to the get event type endpoints params
func (o *GetEventTypeEndpointsParams) SetModelID(modelID string) {
	o.ModelID = modelID
}

// WriteToRequest writes these params to a swagger request
func (o *GetEventTypeEndpointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param event_type
	if err := r.SetPathParam("event_type", o.EventType); err != nil {
		return err
	}

	// path param model_id
	if err := r.SetPathParam("model_id", o.ModelID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
