---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ibmc-s3fs-standard
provisioner: ibm.io/ibmc-s3fs
parameters:
  ibm.io/chunk-size-mb: "10"
  ibm.io/parallel-count: "5"
  ibm.io/tls-cipher-suite: "AES"
  ibm.io/multireq-max: "20"
  ibm.io/stat-cache-size: "100000"
  ibm.io/debug-level: "warn"
  ibm.io/curl-debug: "false"
  ibm.io/kernel-cache: "true"
  ibm.io/s3fs-fuse-retry-count: "5"
