#ibmcloud-object-storage-plugin deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: kube-system
  labels:
    app: {{ .Chart.Name }}
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      tolerations:
      - operator: "Exists"
      serviceAccountName: ibmcloud-object-storage-plugin
      containers:
        - name: {{ .Chart.Name }}-container
{{ if eq .Values.arch "ppc64le" }}
          image: "{{ .Values.image.repository_ppc64le }}:{{ .Values.image.Build }}"
{{ else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.Build }}"
{{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-provisioner=ibm.io/ibmc-s3fs"
          env:
          - name: DEBUG_TRACE
            value: 'false'
