{{ if .Values.dind }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt"
  persistentVolumeReclaimPolicy: Delete
{{ end }}
